name: ğŸš€ Deploy Docs
on:
  push:
    branches:
    - master
#    tags:
#      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ›’ Checkout
      uses: actions/checkout@master
    - name: ğŸ Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: ğŸ§° Install dependencies
      run: make install IGNORE_VENV=1
    - name: ğŸ“š Build Docs
      run: |
        make docs
        touch docs/build/html/.nojekyll
    - name: ğŸš€ Deploy Docs
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: docs/build/html
    #- name: Build Package
      #run: |
        #python3 setup.py sdist
    #- name: Deploy Package
      #uses: pypa/gh-action-pypi-publish@master
      #with:
        #user: __token__
        #password: ${{ secrets.PYPI_TOKEN }}
