name: ğŸ§ª Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ›’ Checkout
      uses: actions/checkout@v3
    - name: ğŸ Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: ğŸ§° Install dependencies
      run: make install IGNORE_VENV=1
    - name: ğŸ‘® Lint
      run: make lint
    - name: ğŸ” Type check
      uses: jakebailey/pyright-action@v1
      with:
        version: 1.1.317
        python-version: '3.10'
    - name: ğŸ§ª Test
      run: make tests
